README.md

It would helpful for new users to be shown some info about how to get set up and using this thing.
For now, this is a placeholder and reminder.

To help onboard new users - basic readme added

---

README.md

Replacing Eddie's now broken shinyapps link

Update README - include working deployment

---

data_generators/DataCreator.R

I've added the keywords to the clusters on the MoJallPQsforTableau.csv, and amended the DataCreator.R file so that it will generate these automatically from now on.
We need to also think about how to incorporate these in the table.

Representing clusters better

---

.travis.yml
data_generators/DataCreator.R

I've added a nameCleaner function that should sort out the name issues. I am not 100% sure that there won't still be edge cases that it misses but I guess we'll deal with those as and when they come up.
It could probably be optimised but it doesn't take too long anyway with only ~600 names.

Fix the issues with names of those asking questions

---

server.R
ui.R

Adding child rows and implementing other design changes
- change date formats
- add more graph interactivity

Add Child Rows

---

Dockerfile
Jenkinsfile

I'm trying to deploy the app to the analytics platform.  This may or may not be all that's required but in order to test that, I think, these files need to be on the master branch.

Files for deploying to platform

---

server.R

Interface changes for SoS demo

---

.Rprofile
.travis.yml
data_generators/DataCreator.R
global.R

Added a few words to stopwords and abstracted the list so that it's in one place and we only need to change it in that one place.

Update and abstract stopwords

---

pq.js
server.R
ui.R

adding link between tabs 2

---

ui.R

This was easier than I thought it would be.

Added placeholder text to searchbox

---

pq.js
ui.R

Plain old javascript to the rescue! jQuery was acting weirdly, so just used the boggest of standards.  Also got rid of unnecessary stuff from ui.R (when I was testing out adding HTML in shiny)

removed d3 dependency, removed a few ugly bits of old code (my code)

---

pq.js
server.R
ui.R

Fixes some of the error messages and styles all tables in the same way.

Fix error messages and tables

---

server.R
ui.R

When I was playing around with the layout I got into a right mess.  Hopefully these tweaks will make future attempts to change the layout easier.  Let me know what you think.

Refactoring UI for readability

---

data_generators/MPClustering.R

Add script for creating allMPs.rda and allTopics.rda

Add MPClustering

---

server.R

so that they come with the most recent first.

Reordered questions on Topic analysis page 

---

pq.js
ui.R

More unsatisfactory hackery.  Calls a function every 20ms to see if the table needs cleaning up to display proper error message.  Because of how table is populated, couldn't think of a way that wouldn't require constantly checking the table.  Note that this also means that it messes with the table very briefly even if it is fine, before immediately correcting it and leaving it alone.

Round-about fix of table issues. Also update plot visibility condition

---

.travis.yml
DESCRIPTION
global.R
packrat/packrat.lock
pq.js
server.R
ui.R

Almost all the work of @RossKen – we now have an awesome walkthrough for the tool.  This branch was created to clean up the commit history without the risk of ruining his hard work.

Fix walkthough

---

pq.js

This should solve the issue with the italic tags- we weren't formatting the question text, only the answer text.

Format question text

---

README.md

What do you think about this? Is it an improvement?
Some changes were needed after I added the new `-e` flag but I've also made some other changes.

Readmetweaks

---

README.md
tests/TESTING.md

Here's a first draft.  Let me know what you think and I will make changes ASAP, if any are needed.

Documentation

---

R/Functions.R
checklist.md
tests/TESTING.md
tests/testthat/test-functions.R

Some small changes, mostly to the .md files that are for QA purposes

Tidy up a bit

---

tests/testthat/test-basic.R
tests/testthat/test-search.R
ui.R

Name change, because comms

---

server.R
tests/testthat/test-search.R

Fix some obvious small mistakes picked up by Hayden's QA

initial commit

---

server.R

Removed duplication from MP_Table and added more info to plot title.
We can now squish that table a bit and add an exciting new feature to the page... what will it be??

Remove duplicative columns from members table

---

server.R

MPs are now grouped by party in the drop down on the member tab.
If you two think this is the right thing to do, I will spend some time making the code nicer.  It's very ugly at the moment but improving it is beyond me today (I tried it and everything broke).

Easier to search MP list when grouped(?)

---

.Rprofile
.travis.yml
README.md
server.R
tests/testthat/test-api-client.R
tests/testthat/test-basic.R
tests/testthat/test-functions.R
tests/testthat/test-search.R
tests/testthat/test-tour.R
ui.R

- hide the next button at the step where the user should progress by clicking on 'see all questions by XYZ'

Sure up and test the intro

---

global.R
server.R

If you agree that this is an improvement I will do the same for the other ggplot histogram (but it's 6pm on a Friday so I will soon be turning off my R brain).

Clean up topic plot code

---

pq.js
server.R

- Clear the search box and reload the page to fix this
- Reload from server not from cache

After tutorial exit a bug on search is generated

---

tests/test-tour.R

This should make these tests pass more reliably on travis

Page loads slower on Travis; wait longer in tests

---

server.R
ui.R

- fixed them so they show in their entirety
- changed it so that words are all horizontally displayed
- changed it so words are displayed from centre out in order of importance

Tarted up wordclouds

---

README.md

To include:
* Adding contents section to make README clearer
* Adding instructions for updating data for all departments
* Adding instructions for updating search space for all departments

Updates to README for general tool
